### ISSUE TITLE
Mejora: Evitar la superposicion de texto del footer con el contenido de la página

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyectos2020-cetti-enders-nunez#15]
No se entiende bien el texto cuando hay superposición
![imagen](https://user-images.githubusercontent.com/8345007/85493514-6a8fcc80-b5ad-11ea-9ac5-46c563e134d1.png)

**Comment by ivanln26** [comment]
En las pruebas realizadas en distintos monitores de 1920x1080 sin hacer zoom y sin la consola de desarrollador abierta no debería haber problemas. De igual manera agregué una columna al grilla de los controles.
