### ISSUE TITLE
Mejora: Agregar botón para parar música

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyectos2020-cetti-enders-nunez#17]

**Comment by ivanln26** [comment]
Disculpe profe, a que se refiere con esta mejora? Ya existe un botón que permite mutear la música arriba a la izquierda del sitio.

**Comment by ivanln26** [comment]
Añadimos la tecla "m" para mutear la música. Y agregamos la imagen representativa en el tutorial.
